### ISSUE TITLE
NAVER Webtoon dataset and pretrained StyleGAN2 model

### ISSUE THREAD

**Issue by betterze** [bryandlee/naver-webtoon-faces#1]
Dear Bryandlee,

Thank you @bryandlee for sharing with us this interesting work.

Would you mind providing the download link for NAVER Webtoon dataset and the StyleGAN2 model that transfer from FFHQ? 

Thank you very much for you help.

Best Wishes,

Alex

**Comment by bryandlee** [comment]
Hi, thanks for your interest. The model file can be downloaded [here](https://drive.google.com/file/d/14JLmYRtUFDbTC4IVzt14Os-tf23BXMLd/view?usp=sharing).

**Comment by betterze** [comment]
Thx a lot. The images look very nice.
