### ISSUE TITLE
Latent vector direction file

### ISSUE THREAD

**Issue by viuts** [bryandlee/naver-webtoon-faces#2]
HI @bryandlee! 

Thank you for the putting this great work up, this look very interesting and promising, I am trying to play with the model you provided, I wonder it is possible that I can also have the vector direction files that you used in [https://github.com/bryandlee/naver-webtoon-faces#4-way-linear-interpolation-in-w-space](url). That would be super helpful!

**Comment by bryandlee** [comment]
Hi, those are actually random directions. The example simply shows the linear interpolation results of four random samples.
