### ISSUE TITLE
face alignment 

### ISSUE THREAD

**Issue by betterze** [bryandlee/naver-webtoon-faces#4]
Dear bryandlee,

Thank you for sharing with us this nice work. Would you mind telling me if you align the cartoon face as people do in ffhq? If so, how you algin the cartoon face? 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by bryandlee** [comment]
Hi, thanks for your interest. I used a cartoon face detector on full cartoon images to get aligned facial images. I simply crop-saved the detected bboxes.

**Comment by betterze** [comment]
Thank you for your reply. I understand it now.
